CREATE TABLE `songs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`slug` text NOT NULL,
	`artist` text NOT NULL,
	`title` text NOT NULL,
	`level` text NOT NULL,
	`price` integer DEFAULT 199 NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`features` text DEFAULT '[]' NOT NULL,
	`key_name` text DEFAULT '' NOT NULL,
	`capo` text DEFAULT '' NOT NULL,
	`barre` integer DEFAULT false NOT NULL,
	`difficulty` integer DEFAULT 1 NOT NULL,
	`video_duration` text DEFAULT '' NOT NULL,
	`pdf_pages` integer DEFAULT 0 NOT NULL,
	`cover_key` text,
	`cover_style` text DEFAULT 'violet' NOT NULL,
	`preview_video_url` text DEFAULT '' NOT NULL,
	`private_video_url` text DEFAULT '' NOT NULL,
	`pdf_key` text,
	`private_pdf_url` text DEFAULT '' NOT NULL,
	`is_new` integer DEFAULT false NOT NULL,
	`is_popular` integer DEFAULT false NOT NULL,
	`popularity` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `songs_slug_unique` ON `songs` (`slug`);