import type { AdminSong, PublicSong } from "./song-types";

export const seedSongs: AdminSong[] = [
  {
    id: 1,
    slug: "kino-pachka-sigaret",
    artist: "Кино",
    title: "Пачка сигарет",
    level: "Начинающий",
    price: 199,
    description: "Полный разбор песни для начинающих: аккорды, бой, переходы и исполнение от начала до конца.",
    features: ["Аккорды", "Бой", "Табулатура"],
    keyName: "Em",
    capo: "Не нужен",
    barre: false,
    difficulty: 1,
    videoDuration: "28 минут",
    pdfPages: 7,
    coverUrl: null,
    coverKey: null,
    coverStyle: "violet",
    previewVideoUrl: "",
    privateVideoUrl: "",
    privatePdfUrl: "",
    pdfKey: null,
    isNew: true,
    isPopular: true,
    popularity: 98,
    status: "published",
    createdAt: "2026-08-12T10:00:00.000Z",
  },
  {
    id: 2,
    slug: "korol-i-shut-lesnik",
    artist: "Король и Шут",
    title: "Лесник",
    level: "Любитель",
    price: 249,
    description: "Разбираем узнаваемый ритм, аккорды, динамику куплетов и уверенную игру под оригинал.",
    features: ["Аккорды", "Бой", "Рифф"],
    keyName: "Am",
    capo: "Не нужен",
    barre: true,
    difficulty: 3,
    videoDuration: "36 минут",
    pdfPages: 9,
    coverUrl: null,
    coverKey: null,
    coverStyle: "ember",
    previewVideoUrl: "",
    privateVideoUrl: "",
    privatePdfUrl: "",
    pdfKey: null,
    isNew: true,
    isPopular: true,
    popularity: 95,
    status: "published",
    createdAt: "2026-08-10T10:00:00.000Z",
  },
  {
    id: 3,
    slug: "nirvana-come-as-you-are",
    artist: "Nirvana",
    title: "Come As You Are",
    level: "Любитель",
    price: 249,
    description: "Фирменный рифф, чистый звук, куплеты и припев — с медленной практикой каждого фрагмента.",
    features: ["Рифф", "Аккорды", "Табулатура"],
    keyName: "Em",
    capo: "Не нужен",
    barre: false,
    difficulty: 2,
    videoDuration: "31 минута",
    pdfPages: 8,
    coverUrl: null,
    coverKey: null,
    coverStyle: "ocean",
    previewVideoUrl: "",
    privateVideoUrl: "",
    privatePdfUrl: "",
    pdfKey: null,
    isNew: false,
    isPopular: true,
    popularity: 92,
    status: "published",
    createdAt: "2026-08-06T10:00:00.000Z",
  },
  {
    id: 4,
    slug: "metallica-nothing-else-matters",
    artist: "Metallica",
    title: "Nothing Else Matters",
    level: "Продвинутый",
    price: 349,
    description: "Подробно собираем вступление, перебор, аккордовую фактуру и выразительную подачу композиции.",
    features: ["Перебор", "Соло", "Табулатура"],
    keyName: "Em",
    capo: "Не нужен",
    barre: true,
    difficulty: 5,
    videoDuration: "1 час 12 минут",
    pdfPages: 16,
    coverUrl: null,
    coverKey: null,
    coverStyle: "silver",
    previewVideoUrl: "",
    privateVideoUrl: "",
    privatePdfUrl: "",
    pdfKey: null,
    isNew: false,
    isPopular: true,
    popularity: 100,
    status: "published",
    createdAt: "2026-07-28T10:00:00.000Z",
  },
  {
    id: 5,
    slug: "kino-zvezda-po-imeni-solntse",
    artist: "Кино",
    title: "Звезда по имени Солнце",
    level: "Начинающий",
    price: 199,
    description: "Простой и музыкальный разбор для первых уверенных песен: аккорды, бой и структура.",
    features: ["Аккорды", "Бой"],
    keyName: "Am",
    capo: "Не нужен",
    barre: false,
    difficulty: 1,
    videoDuration: "24 минуты",
    pdfPages: 6,
    coverUrl: null,
    coverKey: null,
    coverStyle: "sunset",
    previewVideoUrl: "",
    privateVideoUrl: "",
    privatePdfUrl: "",
    pdfKey: null,
    isNew: true,
    isPopular: false,
    popularity: 84,
    status: "published",
    createdAt: "2026-08-11T10:00:00.000Z",
  },
  {
    id: 6,
    slug: "sting-shape-of-my-heart-fingerstyle",
    artist: "Sting",
    title: "Shape of My Heart",
    level: "Фингерстайл",
    price: 399,
    description: "Самодостаточная фингерстайл-аранжировка с мелодией, басом и подробной аппликатурой.",
    features: ["Фингерстайл", "Табулатура", "Перебор"],
    keyName: "F#m",
    capo: "2 лад",
    barre: true,
    difficulty: 4,
    videoDuration: "58 минут",
    pdfPages: 14,
    coverUrl: null,
    coverKey: null,
    coverStyle: "forest",
    previewVideoUrl: "",
    privateVideoUrl: "",
    privatePdfUrl: "",
    pdfKey: null,
    isNew: false,
    isPopular: false,
    popularity: 76,
    status: "published",
    createdAt: "2026-07-24T10:00:00.000Z",
  },
];

export const publicSeedSongs: PublicSong[] = seedSongs
  .filter((song) => song.status === "published")
  .map(({ privateVideoUrl: _video, privatePdfUrl: _pdf, pdfKey: _pdfKey, coverKey: _coverKey, status: _status, ...song }) => song);
